# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_QEYEy3d3b3dteoVw1Nfk1Fgol9_tzC
"""

print("hello world")